In [1]:
import pandas as pd
import glob

In [2]:
csv_files = glob.glob(r'D:\Guvi\Projects\PatrolIQ\*.csv')     # This will create a list of path of each csv file present in my PatrolIQ folder 

list_df = []                                                  # An empty list to store all dataframes
for file in csv_files:
    read = pd.read_csv(file)
    list_df.append(read)

df = pd.concat(list_df, ignore_index=True)                    # create one dataframe

In [3]:
pd.set_option("display.max_columns", None)

In [4]:
df.shape

(8518944, 22)

In [5]:
df.columns

Index(['Case Number', 'Date', 'Block', 'IUCR', 'Primary Type', 'Description',
       'Location Description', 'Arrest', 'Domestic', 'Beat', 'Ward',
       'FBI Code', 'X Coordinate', 'Y Coordinate', 'Year', 'Latitude',
       'Longitude', 'Location', 'ID', 'District', 'Community Area',
       'Updated On'],
      dtype='object')

In [6]:
df.head()

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,Ward,FBI Code,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,ID,District,Community Area,Updated On
0,HL280962,01/01/2001 12:00:00 AM,089XX S BRANDON AVE,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,424,10.0,06,1198833.0,1846473.0,2001,41.733539,-87.547156,POINT (-87.547155925 41.733539408),NaN,NaN,NaN,NaN
1,HR531333,01/01/2001 12:00:00 AM,008XX W MARGATE TER,0840,THEFT,FINANCIAL ID THEFT: OVER $300,APARTMENT,False,False,2024,48.0,06,1169494.0,1933332.0,2001,41.972573,-87.652114,POINT (-87.652114211 41.972573024),NaN,NaN,NaN,NaN
2,G318546,01/01/2001 12:00:00 AM,117XX S ELIZABETH ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,False,524,NaN,26,1170074.0,1826684.0,2001,41.679908,-87.653087,POINT (-87.65308654 41.679907896),NaN,NaN,NaN,NaN
3,HR690758,01/01/2001 12:00:00 AM,023XX S SACRAMENTO AVE,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,False,1033,12.0,06,1156774.0,1888069.0,2001,41.848636,-87.700117,POINT (-87.700116823 41.848635623),NaN,NaN,NaN,NaN
4,G106773,01/01/2001 12:00:00 AM,023XX W HURON ST,1210,DECEPTIVE PRACTICE,THEFT OF LABOR/SERVICES,RESIDENCE,False,False,1313,NaN,11,1160422.0,1904564.0,2001,41.893825,-87.686272,POINT (-87.686272003 41.893824874),NaN,NaN,NaN,NaN

In [7]:
df['Date'] = pd.to_datetime(df['Date'])

C:\Users\abdul\AppData\Local\Temp\ipykernel_5004\2394721818.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date'] = pd.to_datetime(df['Date'])

In [8]:
df['Date'].dtype

dtype('<M8[ns]')

In [9]:
df = df.sort_values(by='Date', ascending=False).reset_index(drop=True)

In [10]:
df.head()

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,Ward,FBI Code,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,ID,District,Community Area,Updated On
0,JK184891,2026-03-18,069XX S CORNELL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,332,5.0,08B,1188552.0,1859230.0,2026,41.768797,-87.584413,POINT (-87.584412909 41.768797328),14139805.0,3.0,43.0,03/25/2026 03:57:05 PM
1,JK184982,2026-03-18,082XX S CORNELL AVE,0820,THEFT,$500 AND UNDER,VEHICLE NON-COMMERCIAL,False,False,411,8.0,06,1188698.0,1850652.0,2026,41.745255,-87.584152,POINT (-87.584151569 41.745255037),14139911.0,4.0,45.0,03/25/2026 03:57:05 PM
2,JK188256,2026-03-18,034XX N RIDGEWAY AVE,0810,THEFT,OVER $500,RESIDENCE,False,False,1732,30.0,06,1150784.0,1922573.0,2026,41.943437,-87.721197,POINT (-87.721197255 41.943437198),14142669.0,17.0,21.0,03/25/2026 03:57:05 PM
3,JK192344,2026-03-18,057XX W ROOSEVELT RD,0460,BATTERY,SIMPLE,HOSPITAL BUILDING / GROUNDS,False,False,1513,29.0,08B,NaN,NaN,2026,NaN,NaN,NaN,14146131.0,15.0,25.0,03/25/2026 03:57:05 PM
4,JK186910,2026-03-18,072XX S DAMEN AVE,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,RESIDENCE,False,False,735,17.0,11,1164278.0,1856611.0,2026,41.762156,-87.673463,POINT (-87.673462943 41.762155987),14141280.0,7.0,67.0,03/25/2026 03:57:05 PM

In [11]:
df.tail()

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,Ward,FBI Code,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,ID,District,Community Area,Updated On
8518939,G000300,2001-01-01,020XX W COULTER ST,0810,THEFT,OVER $500,APARTMENT,False,False,1034,NaN,06,1162946.0,1888131.0,2001,41.848679,-87.677463,POINT (-87.677463341 41.848678639),NaN,NaN,NaN,NaN
8518940,HX403539,2001-01-01,031XX W DOUGLAS BLVD,1562,SEX OFFENSE,AGG CRIMINAL SEXUAL ABUSE,CHURCH/SYNAGOGUE/PLACE OF WORSHIP,False,False,1022,24.0,17,NaN,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8518941,G057402,2001-01-01,034XX W ADAMS ST,1150,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,RESIDENCE,False,False,1123,NaN,11,1153613.0,1898824.0,2001,41.878212,-87.711432,POINT (-87.711432075 41.87821192),NaN,NaN,NaN,NaN
8518942,HX397217,2001-01-01,031XX W DOUGLAS BLVD,1562,SEX OFFENSE,AGG CRIMINAL SEXUAL ABUSE,CHURCH/SYNAGOGUE/PLACE OF WORSHIP,False,False,1022,24.0,17,NaN,NaN,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8518943,HL280962,2001-01-01,089XX S BRANDON AVE,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,424,10.0,06,1198833.0,1846473.0,2001,41.733539,-87.547156,POINT (-87.547155925 41.733539408),NaN,NaN,NaN,NaN

In [12]:
df_sampled = df.head(500000)

In [13]:
df_sampled.shape

(500000, 22)

In [14]:
# After sampling the data got unsorted so we need to sort again

In [15]:
df_sampled.head()

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,Ward,FBI Code,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,ID,District,Community Area,Updated On
0,JK184891,2026-03-18,069XX S CORNELL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,332,5.0,08B,1188552.0,1859230.0,2026,41.768797,-87.584413,POINT (-87.584412909 41.768797328),14139805.0,3.0,43.0,03/25/2026 03:57:05 PM
1,JK184982,2026-03-18,082XX S CORNELL AVE,0820,THEFT,$500 AND UNDER,VEHICLE NON-COMMERCIAL,False,False,411,8.0,06,1188698.0,1850652.0,2026,41.745255,-87.584152,POINT (-87.584151569 41.745255037),14139911.0,4.0,45.0,03/25/2026 03:57:05 PM
2,JK188256,2026-03-18,034XX N RIDGEWAY AVE,0810,THEFT,OVER $500,RESIDENCE,False,False,1732,30.0,06,1150784.0,1922573.0,2026,41.943437,-87.721197,POINT (-87.721197255 41.943437198),14142669.0,17.0,21.0,03/25/2026 03:57:05 PM
3,JK192344,2026-03-18,057XX W ROOSEVELT RD,0460,BATTERY,SIMPLE,HOSPITAL BUILDING / GROUNDS,False,False,1513,29.0,08B,NaN,NaN,2026,NaN,NaN,NaN,14146131.0,15.0,25.0,03/25/2026 03:57:05 PM
4,JK186910,2026-03-18,072XX S DAMEN AVE,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,RESIDENCE,False,False,735,17.0,11,1164278.0,1856611.0,2026,41.762156,-87.673463,POINT (-87.673462943 41.762155987),14141280.0,7.0,67.0,03/25/2026 03:57:05 PM

In [16]:
df_sampled.tail()

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,Ward,FBI Code,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,ID,District,Community Area,Updated On
499995,JH168561,2024-02-28 06:05:00,038XX N ASHLAND AVE,0610,BURGLARY,FORCIBLE ENTRY,BAR OR TAVERN,False,False,1922,47.0,05,1164974.0,1925345.0,2024,41.950754,-87.668963,POINT (-87.668962751 41.950753786),13382369.0,19.0,6.0,12/21/2024 03:40:46 PM
499996,JH171253,2024-02-28 06:00:00,056XX W BYRON ST,0810,THEFT,OVER $500,RESIDENCE,False,False,1633,38.0,06,1138141.0,1925361.0,2024,41.951326,-87.767600,POINT (-87.76759975 41.951326099),13385723.0,16.0,15.0,12/21/2024 03:40:46 PM
499997,JH169057,2024-02-28 06:00:00,060XX S OAK PARK AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,812,13.0,06,1132121.0,1863662.0,2024,41.782122,-87.791162,POINT (-87.791161899 41.782121775),13382822.0,8.0,64.0,12/21/2024 03:40:46 PM
499998,JH169158,2024-02-28 06:00:00,017XX S INDIANA AVE,0890,THEFT,FROM BUILDING,APARTMENT,False,False,132,3.0,06,1177933.0,1891878.0,2024,41.858633,-87.622346,POINT (-87.622346444 41.858633393),13383190.0,1.0,33.0,12/21/2024 03:40:46 PM
499999,JH169156,2024-02-28 06:00:00,017XX S INDIANA AVE,0890,THEFT,FROM BUILDING,APARTMENT,False,False,132,3.0,06,1177933.0,1891878.0,2024,41.858633,-87.622346,POINT (-87.622346444 41.858633393),13383165.0,1.0,33.0,12/21/2024 03:40:46 PM

In [22]:
df_sampled.dtypes

Case Number                     object
Date                    datetime64[ns]
Block                           object
IUCR                            object
Primary Type                    object
Description                     object
Location Description            object
Arrest                            bool
Domestic                          bool
Beat                             int64
Ward                           float64
FBI Code                        object
X Coordinate                   float64
Y Coordinate                   float64
Year                             int64
Latitude                       float64
Longitude                      float64
Location                        object
ID                             float64
District                       float64
Community Area                 float64
Updated On                      object
dtype: object

In [18]:
df_sampled['Primary Type'].unique()

array(['BATTERY', 'THEFT', 'DECEPTIVE PRACTICE', 'BURGLARY',
       'CRIMINAL DAMAGE', 'ASSAULT', 'CRIMINAL TRESPASS',
       'WEAPONS VIOLATION', 'OTHER OFFENSE', 'MOTOR VEHICLE THEFT',
       'INTERFERENCE WITH PUBLIC OFFICER', 'PUBLIC PEACE VIOLATION',
       'ROBBERY', 'NARCOTICS', 'HOMICIDE', 'OFFENSE INVOLVING CHILDREN',
       'SEX OFFENSE', 'CRIMINAL SEXUAL ASSAULT', 'INTIMIDATION', 'ARSON',
       'PROSTITUTION', 'STALKING', 'CONCEALED CARRY LICENSE VIOLATION',
       'KIDNAPPING', 'LIQUOR LAW VIOLATION', 'PUBLIC INDECENCY',
       'HUMAN TRAFFICKING', 'OBSCENITY', 'GAMBLING',
       'OTHER NARCOTIC VIOLATION', 'NON-CRIMINAL'], dtype=object)

In [19]:
df_sampled['IUCR'].unique()[:30]

array(['0486', '0820', '0810', '0460', '1130', '0760', '1153', '1320',
       '0496', '0560', '1330', '1310', '1477', '5111', '0910', '3731',
       '0710', '0430', '2825', '143A', '0860', '051A', '0930', '2870',
       '141A', '0326', '5002', '502R', '5112', '2022'], dtype=object)

In [20]:
df_sampled.to_csv("sampled_crime_data.csv", index=False)

In [21]:
# # Missing values check
# print(df_sampled.isnull().sum())

# # Date missing remove
# df_sample = df_sampled.dropna(subset=['Date'])

# # Categorical columns fill
# cat_cols = ['Primary Type', 'Description', 'Location Description']

# for col in cat_cols:
#     df_sampled[col] = df_sampled[col].fillna('Unknown')

# # Numeric columns fill
# num_cols = ['Beat', 'District', 'Ward', 'Community Area']

# for col in num_cols:
#     df_sampled[col] = df_sample[col].fillna(-1)